spring:
    datasource:
      name: ag_oauth
      url: jdbc:mysql://${MYSQL_HOST:172.16.6.31}:${MYSQL_PORT:3306}/ag_oauth?useUnicode=true&characterEncoding=UTF8
      username: root
      password: root123
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20